### ISSUE TITLE
Add a fuse to speed up resource access

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/postject#58]
See https://github.com/nodejs/node/pull/45038#discussion_r1002031638 cc @mhdawson

> I think we need the concept of a "fuse" here. Something like what I had in [src/node_single_executable_application.cc](https://github.com/nodejs/node/blob/bef9dfcfa940f925b5e994b3f1f4601fe0db7352/src/node_single_executable_application.cc) on line 43, as borrowed from electron.
> 
> That ensures that if you are not using SEA, the overhead is as close to possible as 0. It does mean there is an extra step in the bundling but I don't see that as a big issue.

Do we want to solve this inside postject? It can speed up the resource access calls for the cases where you just wanna know if something has been injected instead of knowing what has been injected into a section.

The only problem I can think of here is that in case there is another occurrence of the sentinel string in the binary, this might confuse postject but that's probably gonna be unlikely if used carefully because the sentinel string is going to have some random bytes in the beginning which should make it hard for that to be repeated somewhere in the binary coincidentally by mistake.

**Comment by ovflowd** [comment]
Is this related to we checking for SEA code to be bundled within Node.js even if no SEA code is present/SEA-cli flag is not present?

**Comment by mhdawson** [comment]
@ovflowd correct. It short circuits the check so that it will only be done if the fuse is set. The result being that when using the Node.js in the regular way there is almost zero additional overhead.

**Comment by ovflowd** [comment]
Then I'm all in for this change to be on postject.

**Comment by RaisinTen** [comment]
Sent a PR to implement this - https://github.com/postmanlabs/postject/pull/59
