### ISSUE TITLE
Can't read and write to target executable

### ISSUE THREAD

**Issue by hd321kbps** [nodejs/postject#82]
I repeated the manual.

2 commands do not work.
Windows 11

![image](https://user-images.githubusercontent.com/9886849/225458792-1aaecb6c-8c14-4ad6-b12f-37630b40649a.png)

**Comment by hd321kbps** [comment]
![image](https://user-images.githubusercontent.com/9886849/225460270-45a13ba9-f06e-48ed-b03f-15269969bbf6.png)
The command only works after manually copying files from C:\Program Files\nodejs\node.exe and after running the command cp $(command -v ./node) hello

**Comment by mattezell** [comment]
What was your resolution @hd321kbps ?

I'm encountering the same "Can't read and write to target executable" error on Windows 11 Powershell when following along with the official docs.

**Comment by mattezell** [comment]
Nevermind....

In case any other Windows users stumble here, specify ".exe" when running the postject command.

`npx postject hello.exe NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
`

**Comment by RaisinTen** [comment]
@mattezell this error happens when postject is unable to access the file it would inject your resource into - https://github.com/nodejs/postject/blob/3edd1dd1e0690167d7db0f502620e41888b2f82e/src/api.js#L20. In this case, the executable name is `hello.exe` but the file name that was being passed to `postject` is `hello`, so that's what caused the error.

**Comment by mattezell** [comment]
Thank you @RaisinTen ! I figured it out a couple of seconds after posting my query here :) Thank you for helping the community - it's helpful to see where in the postject codebase this is happening.

**Comment by Drjacky** [comment]
Same issue on macOS! :/

**Comment by berstend** [comment]
Just in case anyone else runs into this: `chmod 777 hello`

**Comment by jerrygreen** [comment]
I am having this exact error.

**Comment by trufae** [comment]
> Just in case anyone else runs into this: `chmod 777 hello`

safer to use 755
