### ISSUE TITLE
Error: buffer[colonIndex].charCodeAt is not a function

### ISSUE THREAD

**Issue by swz-git** [nodejs/postject#89]
I get this error
```
Start injection of NODE_SEA_BLOB in app.exe...
Error: buffer[colonIndex].charCodeAt is not a function
 ELIFECYCLE  Command failed with exit code 1.
```
from this command `npx postject app.exe NODE_SEA_BLOB ./sea/sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b`.

I'm using node v20.6.1 and postject@1.0.0-alpha.6

**Comment by RaisinTen** [comment]
I think you're missing the `2` at the end of the sentinel fuse. It should be `NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`.

**Comment by swz-git** [comment]
Thanks a lot! I have no idea how I missed that 😅
