### ISSUE TITLE
SEA issue at step running postject to inject the blob

### ISSUE THREAD

**Issue by leiyu2345** [nodejs/postject#94]
**OS:** MacOS Sonoma 14.2.1
**Processor:** Intel

Completely follow the document
https://nodejs.org/api/single-executable-applications.html
Step 6. Inject the blob into the copied binary by running postject
**Command:**
`npx postject hello NODE_SEA_BLOB sea-prep.blob \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    --macho-segment-name NODE_SEA`

**Error:**
Start injection of NODE_SEA_BLOB in hello...
Error: Multiple occurences of sentinel "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2" found in the binary

Anyone can help with this issue? Thanks!

**Comment by tony-go** [comment]
Hi @leiyu2345 

We already track this bug here: https://github.com/nodejs/postject/issues/92
